import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";

const inter = localFont({
  src: "./fonts/InterVF.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700 800 900",
});

const sfCompactDisplay = localFont({
  src: [{
    path: "./fonts/SfCompactDisplayMediumVF.otf",
    weight: "500",
    style: "normal",
  },
  {
    path: "./fonts/SfCompactDisplayThinVF.otf",
    weight: "400",
    style: "normal",
  }],
  variable: "--font-sf-compact-display",
  weight: "400 500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sfCompactDisplay.variable} antialiased`}
      >
        {/* Navbar */}
        <Navbar />
        {/* Main Content */}
        <main className="font-inter space-y-16 sm:space-y-28">
          {children}
        </main>
      </body>
    </html>
  );
}
